const express= require('express')
const product = require('../controllers/productControllers')
const user = require('../controllers/userController')
const wishlist = require('../controllers/wishlistController')
const jwtMiddle = require('../Middlewares/jwtMiddleware')
const cart = require('../controllers/cartController')
const router =new express.Router()

router.get('/all-Products',product.getAllProducts)
router.get('/get-Product/:id',product.getProduct)
router.post('/register',user.userRegister)
router.post('/login',user.userLogin)
router.post('/addToWishlist',jwtMiddle,wishlist.addToWishList)
router.get('/getFromWishlist',jwtMiddle,wishlist.getWishList)
router.delete('/removeFromWishlist/:id',jwtMiddle,wishlist.removeFromWishList)
router.post('/addCart',jwtMiddle,cart.addToCart)
router.get('/getCart',jwtMiddle,cart.getCart)
router.delete('/removeCart/:id',jwtMiddle,cart.removeFromCart)

module.exports = router